title: "&3&lMoonBoard"
lines:
  - "&a&lWelcome to &3&lMoonBoard"
  - "&8&l&m-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
  - "&cThis Plugin is developed by"
  - "&c&lMoonDevelopment"
  - "&8&l&m-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
  - "&c&lVersion: &3&l1.0"
  - "&8&lChange in config.yml"